
import type { Theme } from './types';

export const THEMES: Theme[] = [
  {
    id: 'cyan',
    name: 'Cyan',
    background: 'bg-gradient-to-br from-gray-900 via-black to-gray-800',
    headerBg: 'bg-gray-900/80',
    linkBg: 'bg-gray-800/50',
    linkBorder: 'border-gray-700/80',
    linkHoverBorder: 'hover:border-cyan-400/50',
    linkHoverBg: 'hover:bg-gray-700/70',
    linkHoverIcon: 'group-hover:text-cyan-400',
    linkHoverShadow: 'hover:shadow-cyan-500/20',
    themeSelectorRing: 'ring-cyan-500',
  },
  {
    id: 'rose',
    name: 'Rose',
    background: 'bg-gradient-to-br from-slate-900 via-black to-rose-950/50',
    headerBg: 'bg-slate-900/80',
    linkBg: 'bg-slate-800/50',
    linkBorder: 'border-slate-700/80',
    linkHoverBorder: 'hover:border-rose-400/50',
    linkHoverBg: 'hover:bg-slate-700/70',
    linkHoverIcon: 'group-hover:text-rose-400',
    linkHoverShadow: 'hover:shadow-rose-500/20',
    themeSelectorRing: 'ring-rose-500',
  },
  {
    id: 'emerald',
    name: 'Emerald',
    background: 'bg-gradient-to-br from-gray-900 via-black to-emerald-950/50',
    headerBg: 'bg-gray-900/80',
    linkBg: 'bg-gray-800/50',
    linkBorder: 'border-gray-700/80',
    linkHoverBorder: 'hover:border-emerald-400/50',
    linkHoverBg: 'hover:bg-gray-700/70',
    linkHoverIcon: 'group-hover:text-emerald-400',
    linkHoverShadow: 'hover:shadow-emerald-500/20',
    themeSelectorRing: 'ring-emerald-500',
  },
  {
    id: 'violet',
    name: 'Violet',
    background: 'bg-gradient-to-br from-slate-900 via-black to-violet-950/50',
    headerBg: 'bg-slate-900/80',
    linkBg: 'bg-slate-800/50',
    linkBorder: 'border-slate-700/80',
    linkHoverBorder: 'hover:border-violet-400/50',
    linkHoverBg: 'hover:bg-slate-700/70',
    linkHoverIcon: 'group-hover:text-violet-400',
    linkHoverShadow: 'hover:shadow-violet-500/20',
    themeSelectorRing: 'ring-violet-500',
  },
];
